In [1]:
import numpy as np 

In [7]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [8]:
a.shape

(3,)

In [13]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
c = np.matrix(a)
c

matrix([[1, 2, 3]])

In [18]:
b.shape

(2, 3)

In [21]:
b]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [23]:
m1 = np.random.rand(5000,5000)
m2 = np.random.rand(5000,5000)
x = m1.dot(m2)
for i in range(10000):
    x = m1.dot(x)
    print(i, x.shape)

0 (5000, 5000)
1 (5000, 5000)
2 (5000, 5000)
3 (5000, 5000)
4 (5000, 5000)
5 (5000, 5000)
6 (5000, 5000)
7 (5000, 5000)
8 (5000, 5000)
9 (5000, 5000)
10 (5000, 5000)
11 (5000, 5000)
12 (5000, 5000)
13 (5000, 5000)
14 (5000, 5000)
15 (5000, 5000)
16 (5000, 5000)
17 (5000, 5000)
18 (5000, 5000)
19 (5000, 5000)
20 (5000, 5000)
21 (5000, 5000)
22 (5000, 5000)
23 (5000, 5000)
24 (5000, 5000)
25 (5000, 5000)
26 (5000, 5000)
27 (5000, 5000)
28 (5000, 5000)
29 (5000, 5000)
30 (5000, 5000)
31 (5000, 5000)
32 (5000, 5000)
33 (5000, 5000)
34 (5000, 5000)
35 (5000, 5000)
36 (5000, 5000)
37 (5000, 5000)
38 (5000, 5000)
39 (5000, 5000)
40 (5000, 5000)
41 (5000, 5000)
42 (5000, 5000)
43 (5000, 5000)
44 (5000, 5000)
45 (5000, 5000)


KeyboardInterrupt: 

In [3]:
def sigmoid(z):
    """The sigmoid function."""
    return 1.0/(1.0+np.exp(-z))

for i in range(80000):
    ir = i / 1000.0
    y = sigmoid(ir)
    print("(", i, ",", y ,")")
    if y == 1.0:
        print("Stopped at ", i)
        break

( 0 , 0.5 )
( 1 , 0.5002499999791666 )
( 2 , 0.5004999998333334 )
( 3 , 0.5007499994375005 )
( 4 , 0.5009999986666688 )
( 5 , 0.5012499973958399 )
( 6 , 0.5014999955000162 )
( 7 , 0.5017499928542016 )
( 8 , 0.5019999893334016 )
( 9 , 0.5022499848126231 )
( 10 , 0.5024999791668749 )
( 11 , 0.5027499722711688 )
( 12 , 0.5029999640005184 )
( 13 , 0.5032499542299401 )
( 14 , 0.5034999428344538 )
( 15 , 0.5037499296890819 )
( 16 , 0.5039999146688512 )
( 17 , 0.5042498976487912 )
( 18 , 0.5044998785039364 )
( 19 , 0.5047498571093251 )
( 20 , 0.5049998333399998 )
( 21 , 0.5052498070710082 )
( 22 , 0.5054997781774029 )
( 23 , 0.5057497465342417 )
( 24 , 0.5059997120165879 )
( 25 , 0.5062496744995104 )
( 26 , 0.5064996338580845 )
( 27 , 0.5067495899673914 )
( 28 , 0.5069995427025188 )
( 29 , 0.5072494919385613 )
( 30 , 0.5074994375506203 )
( 31 , 0.5077493794138049 )
( 32 , 0.5079993174032311 )
( 33 , 0.5082492513940231 )
( 34 , 0.5084991812613128 )
( 35 , 0.5087491068802403 )
( 36 , 0.50899902

In [2]:
np.random.randn(10,1)

array([[-0.99625376],
       [-0.57865719],
       [ 0.11299666],
       [ 1.20194177],
       [-0.7055828 ],
       [ 0.83854249],
       [-0.05835013],
       [-0.53056835],
       [-0.26970371],
       [-0.42953301]])