In [2]:
import numpy as np 

In [7]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [8]:
a.shape

(3,)

In [13]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
c = np.matrix(a)
c

matrix([[1, 2, 3]])

In [18]:
b.shape

(2, 3)

In [21]:
b]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [23]:
m1 = np.random.rand(5000,5000)
m2 = np.random.rand(5000,5000)
x = m1.dot(m2)
for i in range(10000):
    x = m1.dot(x)
    print(i, x.shape)

0 (5000, 5000)
1 (5000, 5000)
2 (5000, 5000)
3 (5000, 5000)
4 (5000, 5000)
5 (5000, 5000)
6 (5000, 5000)
7 (5000, 5000)
8 (5000, 5000)
9 (5000, 5000)
10 (5000, 5000)
11 (5000, 5000)
12 (5000, 5000)
13 (5000, 5000)
14 (5000, 5000)
15 (5000, 5000)
16 (5000, 5000)
17 (5000, 5000)
18 (5000, 5000)
19 (5000, 5000)
20 (5000, 5000)
21 (5000, 5000)
22 (5000, 5000)
23 (5000, 5000)
24 (5000, 5000)
25 (5000, 5000)
26 (5000, 5000)
27 (5000, 5000)
28 (5000, 5000)
29 (5000, 5000)
30 (5000, 5000)
31 (5000, 5000)
32 (5000, 5000)
33 (5000, 5000)
34 (5000, 5000)
35 (5000, 5000)
36 (5000, 5000)
37 (5000, 5000)
38 (5000, 5000)
39 (5000, 5000)
40 (5000, 5000)
41 (5000, 5000)
42 (5000, 5000)
43 (5000, 5000)
44 (5000, 5000)
45 (5000, 5000)


KeyboardInterrupt: 